image: php:8.3-cli-alpine

cache:
  paths:
    - vendor/
    - node_modules/

pages:
  stage: deploy
  before_script:
    - apk add --no-cache nodejs npm
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - npm install
    - npm run build
    - mv build_production public
  artifacts:
    paths:
      - public
  only:
    - master